"""Deterministic artifact generators from the C INVENT Canonical Delivery Model."""
from __future__ import annotations
from pathlib import Path
import json, re
import yaml
from cinvent.canonical import CanonicalDeliveryModel

def _safe(s):
    return re.sub(r"[^A-Za-z0-9_-]+", "_", s).strip("_").lower() or "artifact"

def generate_pack(model: CanonicalDeliveryModel, output_dir: str) -> list[dict]:
    root=Path(output_dir)/_safe(model.project)
    root.mkdir(parents=True, exist_ok=True)
    artifacts=[]

    def write(rel, content, kind):
        p=root/rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
        artifacts.append({"path":str(p), "kind":kind})

    write("canonical/canonical_delivery_model.json",
          model.model_dump_json(indent=2), "canonical")

    mapping_rows = ["source_system,source_table,source_column,target_layer,target_table,target_column,transformation,data_type,nullable"]
    for x in model.mappings:
        vals=[x.source_system,x.source_table,x.source_column,x.target_layer,x.target_table,x.target_column,x.transformation,x.data_type,str(x.nullable).lower()]
        mapping_rows.append(",".join('"' + str(v).replace('"','""') + '"' for v in vals))
    write("metadata/source_target_mapping.csv", "\n".join(mapping_rows)+"\n", "metadata")

    dq={"schema_version":"1.0","rules":[x.model_dump() for x in model.quality_rules]}
    write("quality/data_quality_rules.yaml", yaml.safe_dump(dq, sort_keys=False), "quality")

    pipelines={"schema_version":"1.0","pipelines":[x.model_dump() for x in model.pipelines]}
    write("pipelines/pipelines.yaml", yaml.safe_dump(pipelines, sort_keys=False), "pipeline")

    bronze = """# Generated by C INVENT
# Bronze: preserve source fidelity; do not embed business rules here.
from pyspark.sql import functions as F

SOURCE = "<SOURCE_TABLE>"
BRONZE = "<BRONZE_TABLE>"

df = spark.table(SOURCE)
(
    df.withColumn("_cinvent_ingested_at", F.current_timestamp())
      .write.format("delta")
      .mode("append")
      .saveAsTable(BRONZE)
)
"""
    write("notebooks/01_bronze_ingestion.py", bronze, "notebook")

    silver = """# Generated by C INVENT
from pyspark.sql import functions as F, Window

SOURCE = "<BRONZE_TABLE>"
TARGET = "<SILVER_TABLE>"

df = spark.table(SOURCE)

# Replace with canonical business key and source-specific transformations.
w = Window.partitionBy("<BUSINESS_KEY>").orderBy(F.col("_cinvent_ingested_at").desc())
silver = (
    df.withColumn("_rn", F.row_number().over(w))
      .filter(F.col("_rn") == 1)
      .drop("_rn")
)

silver.write.format("delta").mode("overwrite").saveAsTable(TARGET)
"""
    write("notebooks/02_silver_conformance.py", silver, "notebook")

    gold_tables = [x.name for x in model.data_products for x in x.gold_tables]
    gold = f"""-- Generated by C INVENT
-- Gold/business-ready SQL skeleton.
CREATE OR REPLACE VIEW <GOLD_SCHEMA>.business_summary AS
SELECT
  *
FROM <SILVER_SCHEMA>.<SILVER_TABLE>;
"""
    if gold_tables:
        gold += "\n-- Expected Gold tables:\n" + "\n".join(f"-- {x}" for x in gold_tables) + "\n"
    write("sql/03_gold_business_model.sql", gold, "sql")

    tests = """# Generated by C INVENT
import pytest

def test_schema_contract(spark):
    # Replace placeholders with the canonical target table.
    df = spark.table("<SILVER_TABLE>")
    assert df is not None

def test_no_duplicate_business_keys(spark):
    df = spark.table("<SILVER_TABLE>")
    dup = df.groupBy("<BUSINESS_KEY>").count().filter("count > 1").count()
    assert dup == 0
"""
    write("tests/test_data_product.py", tests, "test")

    dlt = {
        "resources": {
            "pipelines": [
                {
                    "name": _safe(model.project)+"_lakeflow",
                    "libraries": [{"notebook": {"path": "notebooks/01_bronze_ingestion.py"}}],
                    "configuration": {"cinvent.project": model.project, "cinvent.schema_version": model.schema_version},
                    "continuous": False,
                    "development": True
                }
            ]
        }
    }
    write("platforms/databricks/lakeflow.pipeline.yml", yaml.safe_dump(dlt, sort_keys=False), "databricks")

    databricks_sql = """-- C INVENT Databricks deployment skeleton
CREATE CATALOG IF NOT EXISTS <CATALOG>;
CREATE SCHEMA IF NOT EXISTS <CATALOG>.bronze;
CREATE SCHEMA IF NOT EXISTS <CATALOG>.silver;
CREATE SCHEMA IF NOT EXISTS <CATALOG>.gold;
"""
    write("platforms/databricks/catalog_setup.sql", databricks_sql, "databricks")

    fabric = """# C INVENT Microsoft Fabric deployment manifest
platform: microsoft_fabric
oneLake:
  lakehouse: <LAKEHOUSE>
layers:
  - bronze
  - silver
  - gold
orchestration:
  type: data_factory
"""
    write("platforms/fabric/deployment.yaml", fabric, "fabric")

    snowflake = """-- C INVENT Snowflake deployment skeleton
CREATE DATABASE IF NOT EXISTS <DATABASE>;
CREATE SCHEMA IF NOT EXISTS <DATABASE>.BRONZE;
CREATE SCHEMA IF NOT EXISTS <DATABASE>.SILVER;
CREATE SCHEMA IF NOT EXISTS <DATABASE>.GOLD;
"""
    write("platforms/snowflake/deployment.sql", snowflake, "snowflake")

    aws = """# C INVENT AWS deployment skeleton
cloud: aws
storage:
  raw: s3://<BUCKET>/raw/
  curated: s3://<BUCKET>/curated/
catalog: glue
governance: lake_formation
analytics: redshift
"""
    write("platforms/aws/deployment.yaml", aws, "aws")

    readme = f"""# C INVENT Delivery Pack — {model.project}

Customer: {model.customer}
Domain: {model.domain}
Platform recommendation: {model.platform_decision.platform}
Cloud: {model.platform_decision.cloud}

## Generated artifacts
- canonical/canonical_delivery_model.json
- metadata/source_target_mapping.csv
- quality/data_quality_rules.yaml
- pipelines/pipelines.yaml
- notebooks/01_bronze_ingestion.py
- notebooks/02_silver_conformance.py
- sql/03_gold_business_model.sql
- tests/test_data_product.py
- platform deployment skeletons

## Safety
These artifacts are generated templates/skeletons. Replace placeholders and run through C INVENT approval, environment validation and platform-specific CI/CD before production execution.
"""
    write("README.md", readme, "documentation")
    return artifacts
